name: Build

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-2022

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Configure
        run: cmake --preset vs2022

      - name: Build
        run: cmake --build --preset release
